[project]
name = "adk-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk[a2a,eval]>=1.19.0",
    "pytest>=9.0.1",
]

[tool.setuptools]
py-modules = ["main", "agents"]
